version: "2.1"
services:
  leanote:
    image: userbo/leanote-app
    #build:
      #context: .
      #dockerfile: Dockerfile
    volumes:
      - "./conf/app.conf:/go/src/github.com/leanote/leanote/conf/app.conf"
      - './data/leanote/log:/var/log'
      - "./data/files/:/go/src/github.com/leanote/leanote/files/"
      - "./data/public/upload/:/go/src/github.com/leanote/leanote/public/upload/"
    ports:
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    image: userbo/leanote-mongodb
    #build:
      #context: .
      #dockerfile: Dockerfile.mongodb
    entrypoint: "/bin/bash"
    command:
      - "/root/start-db.sh"
    healthcheck:
      test: "echo 'db.stats().ok' | mongo 127.0.0.1:27017/leanote --quiet"
    volumes:
      - "./data/mongodb:/data/db"
